// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models;

public partial class Resume
{
    public int ResumeId { get; set; }

    public string UrlResume { get; set; }

    public int? AccountId { get; set; }

    public virtual Account Account { get; set; }
}