// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessObject.Models;

public partial class AccountJobSkill
{
    public int AccountJobSkillId { get; set; }

    public int? AccountId { get; set; }

    public int? JobSkillId { get; set; }

    public string Experience { get; set; }

    public virtual Account Account { get; set; }

    public virtual JobSkill JobSkill { get; set; }
}