// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessObject.Models;

public partial class Account
{
    public int AccountId { get; set; }

    public string PasswordHash { get; set; }

    public string Email { get; set; }

    public DateTime? DateCreate { get; set; }

    public string AccessToken { get; set; }

    public int? RoleId { get; set; }

    public virtual ICollection<AccountJobkill> AccountJobkills { get; set; } = new List<AccountJobkill>();

    public virtual ICollection<Certificate> Certificates { get; set; } = new List<Certificate>();

    public virtual ICollection<Hr> Hrs { get; set; } = new List<Hr>();

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();

    public virtual Role Role { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}