// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessObject.Models;

public partial class Cv
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string UrlCv { get; set; }

    public int? UserId { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual User User { get; set; }
}