// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessObject.Models;

public partial class Educate
{
    public int EducateId { get; set; }

    public string EducateName { get; set; }

    public string Description { get; set; }

    public DateOnly? Date { get; set; }

    public int? AccountId { get; set; }

    public virtual Account Account { get; set; }
}