// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessObject.Models;

public partial class Hr
{
    public int HrId { get; set; }

    public string Fullname { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Position { get; set; }

    public string Status { get; set; }

    public int? AccountId { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<InterviewProcess> InterviewProcesses { get; set; } = new List<InterviewProcess>();
}