// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessObject.Models;

public partial class InterviewProcess
{
    public int ProcessId { get; set; }

    public int? RoundNumber { get; set; }

    public DateTime? DateCreated { get; set; }

    public string Details { get; set; }

    public string Status { get; set; }

    public int? RecruiterId { get; set; }

    public int? ApplicantId { get; set; }

    public virtual Application Applicant { get; set; }

    public virtual Hr Recruiter { get; set; }
}