// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessObject.Models;

public partial class JobJobSkill
{
    public int Id { get; set; }

    public int? JobId { get; set; }

    public int? JobSkillId { get; set; }

    public string ExperienceRequired { get; set; }

    public virtual Job Job { get; set; }

    public virtual JobSkill JobSkill { get; set; }
}