// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessObject.Models;

public partial class JobSkill
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<AccountJobSkill> AccountJobSkills { get; set; } = new List<AccountJobSkill>();

    public virtual ICollection<JobJobSkill> JobJobSkills { get; set; } = new List<JobJobSkill>();
}