// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessObject.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Gender { get; set; }

    public string Fullname { get; set; }

    public string Phone { get; set; }

    public string Location { get; set; }

    public DateTime? DateCreate { get; set; }

    public int? AccountId { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Cv> Cvs { get; set; } = new List<Cv>();
}